### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by pincher2012** [BrownBear2/atom-save-all#1]
[Enter steps to reproduce below:]
1. Press ctrl + s

**Atom Version**: 1.0.0
**System**: Windows 8.1 x64
**Thrown From**: [atom-save-all](https://github.com/BrownBear2/atom-save-all) package, v0.4.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\куаку\.atom\packages\atom-save-all\lib\atom-save-all.coffee:11

TypeError: undefined is not a function
  at Object.module.exports.AtomSaveAll.saveAll (C:\Users\куаку\.atom\packages\atom-save-all\lib\atom-save-all.coffee:11:30)
  at atom-text-editor.<anonymous> (C:\Users\куаку\.atom\packages\atom-save-all\lib\atom-save-all.coffee:6:72)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\куаку\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\куаку\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\куаку\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\куаку\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\куаку\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```
### Commands

```
     -1:00.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  2x -0:59.6.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:58.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.5.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:51.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:22 core:move-right (atom-text-editor.editor.is-focused)
     -0:18.4.0 core:move-left (atom-text-editor.editor.is-focused)
 10x -0:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.7.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -0:08.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:08.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:05.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "d:\\openserver\\domains"
  }
}
```
### Installed Packages

``` coffee
# User
atom-save-all, v0.4.0
emmet, v2.3.12

# Dev
No dev packages
```

**Comment by BrownBear2** [comment]
fixed in 0.4.1
