### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/papajohn/repos/udemyrails/first/app/contro...

### ISSUE THREAD

**Issue by rssawhney** [BrownBear2/atom-save-all#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0-beta8
**System**: Ubuntu 14.04.4
**Thrown From**: [atom-save-all](https://github.com/BrownBear2/atom-save-all) package, v0.4.1
### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/papajohn/repos/udemyrails/first/app/controllers/articles_controller.rb'

```
At /usr/local/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1068

Error: EACCES: permission denied, open '/home/papajohn/repos/udemyrails/first/app/controllers/articles_controller.rb'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.fsPlus.writeFileSync (/usr/local/share/atom-beta/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/local/share/atom-beta/resources/app.asar/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/local/share/atom-beta/resources/app.asar/node_modules/pathwatcher/lib/file.js:398:21)
    at File.module.exports.File.writeSync (/usr/local/share/atom-beta/resources/app.asar/node_modules/pathwatcher/lib/file.js:355:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/local/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:19)
    at TextBuffer.module.exports.TextBuffer.save (/usr/local/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1043:19)
    at TextEditor.module.exports.TextEditor.save (/usr/local/share/atom-beta/resources/app.asar/src/text-editor.js:629:26)
    at Object.module.exports.AtomSaveAll.saveAll (/home/papajohn/.atom/packages/atom-save-all/lib/atom-save-all.coffee:18:18)
    at atom-text-editor.<anonymous> (/home/papajohn/.atom/packages/atom-save-all/lib/atom-save-all.coffee:6:72)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at /usr/local/share/atom-beta/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom-beta/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/local/share/atom-beta/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/local/share/atom-beta/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:55.2.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
  3x -4:41.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -4:40.3.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -4:39.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:39.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:39.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -4:36.1.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -3:51.5.0 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -3:46 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:03.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:03.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -3:01.1.0 core:delete (atom-text-editor.editor.is-focused)
  5x -3:00.7.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:57 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -1:42.8.0 core:undo (atom-text-editor.editor.is-focused)
 23x -1:39.6.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax-dark, v0.2.3
atom-save-all, v0.4.1
color-picker, v2.1.1
file-icons, v1.6.18
highlight-selected, v0.11.2
linter, v1.11.3
pigments, v0.24.5
seti-ui, v0.9.1

# Dev
No dev packages
```

**Comment by BrownBear2** [comment]
I assume you had opened a file that you had no write access to. I guess it should not save these files ie. ignore the exception?
