### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '/home/me/work/liveu/py/videogateway/video/stream...

### ISSUE THREAD

**Issue by raanand-home** [BrownBear2/atom-save-all#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 12.04.5
**Thrown From**: [atom-save-all](https://github.com/BrownBear2/atom-save-all) package, v0.4.1
### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/me/work/liveu/py/videogateway/video/streamrelay.py'

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1099

Error: EACCES: permission denied, open '/home/me/work/liveu/py/videogateway/video/streamrelay.py'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:282:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:420:21)
    at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:377:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1090:19)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1074:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Object.module.exports.AtomSaveAll.saveAll (/home/me/.atom/packages/atom-save-all/lib/atom-save-all.coffee:18:18)
    at atom-text-editor.<anonymous> (/home/me/.atom/packages/atom-save-all/lib/atom-save-all.coffee:6:72)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:53.1.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
  2x -0:52.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:51.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:51 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
  2x -0:49.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:48 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -0:38.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:37 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.9.0 core:backspace (atom-text-editor.editor)
     -0:35.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:34.4.0 command-palette:toggle (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:32.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.7.0 core:save (atom-text-editor.editor.autocomplete-active)
     -0:03.4.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.6.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
atom-save-all, v0.4.1
autocomplete-clang, v0.9.3
autocomplete-python, v1.7.2
build, v0.60.0
build-make, v0.9.0
custom-invisibles, v0.1.2
language-dot, v1.6.0
language-latex, v0.6.1
latex-autocomplete, v0.4.2
open-recent, v5.0.0

# Dev
No dev packages
```

**Comment by tchesa** [comment]
Same error. Atom v1.11.2

**Comment by BrownBear2** [comment]
Can't reproduce. Did you maybe not have write permissions?
